name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - foxy
      - humble
  pull_request:
    branches:
      - foxy
      - humble

env:
 ROS_DISTRO: ${{ github.head_ref || github.ref_name }}

jobs:
  industrial_ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ROS_REPO: [testing, main]
    env:
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
        env:
          DOWNSTREAM_WORKSPACE: "github:LeoRover/leo_desktop-ros2#${{ env.ROS_DISTRO }}"

  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:jammy
    strategy:
      fail-fast: false
      matrix:
        linter: [lint_cmake, xmllint]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: humble
          linter: ${{ matrix.linter }}
          package-name: |
            leo
            leo_description
            leo_msgs
            leo_teleop
